name: Build and Deploy Fruit App

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Build Check
        run: |
          python -m py_compile backend/app.py

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd ~/fruit-app
            git pull
            sudo systemctl restart fruit-app
            sudo systemctl reload nginx